In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import importlib

In [4]:
import vsms
import torch
import torch.nn as nn

In [5]:
import clip

In [173]:
from vsms import *

In [174]:
from vsms import BoxFeedbackQuery

In [39]:
class StringEncoder(object):
    def __init__(self):
        variant ="ViT-B/32"
        device='cpu'
        jit = False
        self.device = device
        model, preproc = clip.load(variant, device=device,  jit=jit)
        self.model = model
        self.preproc = preproc
        self.celoss = nn.CrossEntropyLoss(reduction='none')
        
    def encode_string(self, string):
        model = self.model.eval()
        with torch.no_grad():
            ttext = clip.tokenize([string])
            text_features = model.encode_text(ttext.to(self.device))
            text_features = text_features / text_features.norm(dim=-1, keepdim=True)
            return text_features.detach().cpu().numpy()

def get_text_features(self, actual_strings, target_string):        
    s2id = {}
    sids = []
    s2id[target_string] = 0
    for s in actual_strings:
        if s not in s2id:
            s2id[s] = len(s2id)

        sids.append(s2id[s])

    strings = [target_string] + actual_strings
    ustrings = list(s2id)
    stringids = torch.tensor([s2id[s] for s in actual_strings], dtype=torch.long).to(self.device)
    tstrings = clip.tokenize(ustrings)
    text_features = self.model.encode_text(tstrings.to(self.device))
    text_features = text_features / text_features.norm(dim=-1, keepdim=True)
    return text_features, stringids, ustrings
        
def forward(self, imagevecs, actual_strings, target_string):
    ## uniquify strings    
    text_features, stringids, ustrings = get_text_features(self, actual_strings, target_string)

    image_features = torch.from_numpy(imagevecs).type(text_features.dtype)
    image_features = image_features / image_features.norm(dim=-1, keepdim=True)
    image_features = image_features.to(self.device)
    scores = image_features @ text_features.t()
    
    assert scores.shape[0] == stringids.shape[0]
    return scores, stringids.to(self.device), ustrings

def forward2(self, imagevecs, actual_strings, target_string):
    text_features, stringids, ustrings = get_text_features(self, actual_strings, target_string)
    actual_vecs = text_features[stringids]
    sought_vec = text_features[0].reshape(1,-1)
    
    image_features = torch.from_numpy(imagevecs).type(text_features.dtype)
    image_features = image_features / image_features.norm(dim=-1, keepdim=True)
    image_features = image_features.to(self.device)

    search_score = image_features @ sought_vec.reshape(-1)
    confounder_score = (image_features * actual_vecs).sum(dim=1)
    return search_score, confounder_score
    
import torch.optim


In [8]:
import torch.nn.functional as F

In [9]:
nn.HingeEmbeddingLoss()

HingeEmbeddingLoss()

In [11]:
import ray
ray.init('auto')
xclip = ModelService(ray.get_actor('clip'))

2021-06-28 20:33:25,629	INFO worker.py:640 -- Connecting to existing Ray cluster at address: 192.168.1.18:6379


In [12]:
from vsms import *
benchparams = dict(
    objectnet=dict(loader=objectnet_cropped, idxs=np.load('./data/object_random_idx.npy')[:10000])
)

def load_ds(evs, dsnames):
    for k,v in tqdm(benchparams.items(), total=len(benchparams)):
        if k in dsnames:
            def closure():
                ev0 = v['loader'](xclip)
                idxs = v['idxs']
                idxs = np.sort(idxs) if idxs is not None else None
                ev = extract_subset(ev0, idxsample=idxs)
                evs[k] = ev
            closure()

In [13]:
evs = {}
load_ds(evs, 'objectnet')

  0%|          | 0/1 [00:00<?, ?it/s]

In [14]:
ev = evs['objectnet']

In [180]:
vecs = ev.embedded_dataset
hdb = AugmentedDB(raw_dataset=ev.image_dataset, embedding=ev.embedding,
                  embedded_dataset=vecs, vector_meta=ev.fine_grained_meta)

In [166]:
def show_scores(se, vecs, actual_strings, target_string):
    with torch.no_grad():
        se.model.eval()
        scs,stids,rawstrs = forward(se, vecs, actual_strings, target_string=target_string)
    scdf = pd.DataFrame({st:col  for  st,col in zip(rawstrs,scs.cpu().numpy().transpose())})
    display(scdf.style.highlight_max(axis=1))

def get_feedback(idxbatch):
    strids = np.where(ev.query_ground_truth.iloc[idxbatch])[1]
    strs = ev.query_ground_truth.columns[strids]
    strs = [search_terms['objectnet'][fbstr] for fbstr in strs.values]
    return strs

In [167]:
curr_firsts = pd.read_parquet('./data/cats_objectnet_ordered.parquet')

In [175]:
class Updater(object):
    def __init__(self, se, lr, rounds=1, losstype='hinge'):
        self.se = se
        self.losstype=losstype
        self.opt = torch.optim.AdamW([{'params': se.model.ln_final.parameters()},
                          {'params':se.model.text_projection},
#                          {'params':se.model.transformer.parameters(), 'lr':lr*.01}
                                     ], lr=lr, weight_decay=0.)
#        self.opt = torch.optim.Adam@([{'params': se.model.parameters()}], lr=lr)
        self.rounds = rounds
        
    def update(self, imagevecs, actual_strings, target_string):
        se = self.se
        se.model.train()
        losstype = self.losstype
        opt = self.opt
        margin = .3

        def opt_closure():
            opt.zero_grad()            
            if losstype=='ce':
                scores, stringids, rawstrs = forward(se, imagevecs, actual_strings, target_string)
                # breakpoint()
                iidx = torch.arange(scores.shape[0]).long()
                actuals = scores[iidx, stringids]
                midx = scores.argmax(dim=1)
                maxes = scores[iidx, midx]                
            elif losstype=='hinge':
                #a,b = forward2(se, imagevecs, actual_strings, target_string)
                scores, stringids, rawstrs = forward(se, imagevecs, actual_strings, target_string)
                # breakpoint()
                iidx = torch.arange(scores.shape[0]).long()
                maxidx = scores.argmax(dim=1)
                
                actual_score = scores[iidx, stringids].reshape(-1,1)
                #max_score = scores[iidx, maxidx]
                
                
                #target_score = scores[:,0]
                losses1 = F.relu(- (actual_score - scores - margin))
                #losses2 = F.relu(- (actual_score - target_score - margin))
                #losses = torch.cat([losses1, losses2])
                losses = losses1
            else:
                assert False
            loss = losses.mean()
            #print(loss.detach().cpu())
            loss.backward()

        for _ in range(self.rounds):
            opt.step(opt_closure)



def closure(search_query, max_n, firsts, show_display=False, batch_size=10):
    sq = search_terms['objectnet'][search_query]
    se = StringEncoder()
    up = Updater(se, lr=.0001, rounds=1)
    bs = batch_size
    bfq = BoxFeedbackQuery(hdb, batch_size=bs, auto_fill_df=None)
    tvecs = []
    dbidxs = []
    accstrs = []
    gts = []
    while True:
        tvec = se.encode_string(sq)
        tvecs.append(tvec)
        idxbatch, _ = bfq.query_stateful(mode='dot', vector=tvec, batch_size=bs)
        dbidxs.append(idxbatch)
        gtvals = ev.query_ground_truth[search_query][idxbatch].values
        gts.append(gtvals)
        if show_display:
            display(hdb.raw.show_images(idxbatch))
            display(gtvals)
        #vecs = ev.embedded_dataset[idxbatch]
        actual_strings = get_feedback(idxbatch)
        accstrs.extend(actual_strings)

        if show_display:
            display(actual_strings)
        if gtvals.sum() > 0 or len(accstrs) > max_n:
            break

    #     vcs = ev.embedded_dataset[idxbatch]
    #     astrs = actual_strings    
        vcs = ev.embedded_dataset[np.concatenate(dbidxs)]
        astrs = accstrs

        if show_display:
            show_scores(se, vcs, astrs, target_string=sq)
            
        up.update(vcs, actual_strings=astrs, target_string=sq)

        if show_display:
            show_scores(se, vcs, astrs, target_string=sq)


    frsts = np.where(np.concatenate(gts).reshape(-1))[0]
    if frsts.shape[0] == 0:
        firsts[search_query] = np.inf
    else:
        firsts[search_query] = frsts[0] + 1

In [176]:
cf = curr_firsts[curr_firsts.nfirst_x > batch_size]

In [182]:
x.category

'eraser (white board)'

In [181]:
firsts = {}
batch_size = 10
for x in tqdm(curr_firsts.itertuples()):
    closure(x.category, max_n=30, firsts=firsts, show_display=True, batch_size=batch_size)
    print(firsts[x.category], x.nfirst_x)
    if x.nfirst_x <= batch_size:
        break

0it [00:00, ?it/s]

MImageGallery(image_urls=['http://clauslocal:8000//nvme_drive/orm/nbs/vloop_notebooks/data/objectnet/images/sp…

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

['sponge',
 'butter',
 'pencil',
 'ice',
 'paper towel',
 'thermometer',
 'floss container',
 'shampoo bottle',
 'paper towel',
 'marker']

MImageGallery(image_urls=['http://clauslocal:8000//nvme_drive/orm/nbs/vloop_notebooks/data/objectnet/images/sp…

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

['speaker',
 'plastic cup',
 'closed document folder',
 'floss container',
 'butter',
 'bottle cap',
 'floss container',
 'first aid kit',
 'ruler',
 'flashlight']

MImageGallery(image_urls=['http://clauslocal:8000//nvme_drive/orm/nbs/vloop_notebooks/data/objectnet/images/pe…

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

['peeler',
 'thermometer',
 'nail clippers',
 'coaster',
 'glue container',
 'floss container',
 'chess piece',
 'box',
 'closed document folder',
 'envelope']

KeyboardInterrupt: 

In [147]:
firsts = {}
batch_size = 10
for x in tqdm(curr_firsts.itertuples()):
    closure(x.category, max_n=3*x.nfirst_x, firsts=firsts, show_display=True, batch_size=batch_size)
    print(firsts[x.category], x.nfirst_x)
    if x.nfirst_x <= batch_size:
        break

0it [00:00, ?it/s]

66 84.0
33 62.0
37 56.0
41 50.0
40 43.0
109 42.0
35 38.0
43 36.0
23 31.0
32 26.0
22 25.0
20 21.0
19 19.0
30 18.0
11 14.0
14 14.0
14 14.0
13 13.0
13 13.0
11 12.0
16 11.0
10 11.0
13 11.0
12 11.0
10 10.0


In [157]:
rdf = pd.concat([pd.Series(firsts).rename('feedback'), cf[['category', 'nfirst_x']].set_index('category')['nfirst_x'].rename('no_feedback')], axis=1)

In [158]:
((rdf.feedback < rdf.no_feedback).mean(), 
(rdf.feedback == rdf.no_feedback).mean(), 
 (rdf.feedback > rdf.no_feedback).mean())

(0.48, 0.2, 0.28)

In [171]:
rdf

feedback  no_feedback
eraser (white board)        66         84.0
placemat                    33         62.0
hairclip                    37         56.0
bookend                     41         50.0
extension cable             40         43.0
walker                     109         42.0
can opener                  35         38.0
removable blade             43         36.0
squeeze bottle              23         31.0
nail (fastener)             32         26.0
tarp                        22         25.0
sweater                     20         21.0
cd case                     19         19.0
flour container             30         18.0
mixing / salad bowl         11         14.0
battery                     14         14.0
stopper (sink/tub)          14         14.0
tissue                      13         13.0
power bar                   13         13.0
contact lens case           11         12.0
letter opener               16         11.0
vase                        10         11.0
scrub brush                 13         11.0
nut for a screw             12         11.0
binder (closed)             10          NaN

In [183]:
rdf.to_parquet('./data/objectnet_nfirst_verbal.parquet')